import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "Shinomura Hayato",
  title: "Shinomura Hayato | Full Stack Developer",
  description: "Hi, I'm Shinomura Hayato, a passionate Full Stack Developer based in Fukuoka. I craft elegant, high-performance, and user-centric applications, specializing in web development, database management, and continuous learning to deliver impactful digital solutions.",
  origin: "https://brightlearn.onrender.com",
  keywords: [
    "Shinomura Hayato",
    "Full Stack Developer",
    "Web Development Expert",
    "Database Management Specialist",
    "Continuous Learner",
    "Web Developer",
    "Software Development",
    "Fukuoka",
    "Shinomura Hayato portfolio",
    "Shinomura Hayato projects",
    "Shinomura Hayato skills",
    "Shinomura Hayato contact",
    "C",
    "C++",
    "C#",
    "JavaScript",
    "PHP",
    "Python",
    "HTML5",
    "CSS3",
    "Bootstrap",
    "NodeJS",
    "MySQL",
    "PostgreSQL",
    "Firebase",
    "Flask",
    "Render",
    "Photoshop",
    "Filebase",
    "Docker",
    "Git",
    "VS Code",
    "Web Development",
    "Database Management",
    "GitHub",
    "UI/UX",
    "Responsive Design"
  ],
  og: "https://brightlearn.onrender.com/og.png",
  creator: {
    name: "Shinomura Hayato",
    url: "https://brightlearn.onrender.com",
  },
  socials: {
    github: "https://github.com/hayato-shino05",
    x: "https://www.x.com/hayato_shino05",
  },
  siteUrl: "https://brightlearn.onrender.com",
};