import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "Shinomura Hayato",
  title: "Shinomura Hayato | Programming Student",
  description: "Hello there! I'm a passionate programming student who's always eager to learn and grow. I have experience with languages like JavaScript, Python, C++, C#, VB.NET, and PHP, as well as web development with React and Node.js. I'm also skilled in Microsoft Office applications for office tasks.",
  origin: "https://brightlearn.onrender.com",
  keywords: [
    "Shinomura Hayato",
    "Programming Student",
    "Web Development",
    "JavaScript",
    "Python",
    "C++",
    "C#",
    "VB.NET",
    "PHP",
    "React",
    "Next.js",
    "Node.js",
    "Flask",
    "Bootstrap",
    "MySQL",
    "PostgreSQL",
    "Firebase",
    "Microsoft Office",
    "Word",
    "Excel",
    "PowerPoint",
    "Office Skills",
    "Git",
    "GitHub",
    "VS Code",
    "Visual Studio",
    "Docker",
    "Render",
    "Photoshop"
  ],
  og: "https://brightlearn.onrender.com/og.png",
  creator: {
    name: "Shinomura Hayato",
    url: "https://brightlearn.onrender.com",
  },
  socials: {
    github: "https://github.com/hayato-shino05",
    x: "https://www.x.com/hayato_shino05",
  },
  siteUrl: "https://brightlearn.onrender.com",
};